### ISSUE TITLE
Add an option to return Base64 encoded CAPTCHA images

### ISSUE THREAD

**Issue by vipersec** [trekjs/captcha#2]
It should be nice to add an option to return the captcha image encoded with `base64` so they can be easily embedded on a webpage, for example:
`<img alt="Embedded Image" src="data:image/gif;base64,iVBORw0KGgoAAAANSUhEUgAAADIA..." />`

**Comment by fundon** [comment]
Try `buffer.toString('base64')`.

**Comment by vladkalyuzhny** [comment]
```
`data:image/gif;base64,${result.buffer.toString('base64')}`
```
